os:
    - linux
language: node_js
node_js:
    - "6.11.0"
install:
    - npm install -g swagger-tools
script:
    - swagger-tools validate swagger.json
    - swagger-tools validate swagger_access_token.json

